In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
X = np.array([ [0, 0, 1],
               [0, 1, 1],
               [1, 1, 0],
               [1, 0, 0] ])

y = np.array([ [0],
               [0],
               [1],
               [1] ])

w = np.array([ [.50],
               [.50],
               [.50] ])

In [14]:
class NeuralNetwork:
    
    def __init__(self, inputs, outputs, weights):
        self.inputs  = inputs
        self.outputs = outputs
        self.weights = weights
    
    def sigmoid(self, x, deriv=False):
        if deriv == True:
            return x * (1 - x)
        return 1 / ( 1 + np.exp(-x))
    
    def train(self, epochs):
        print('Before Training:')
        print('Weights: \n', self.weights)
        
        for epoch in range(epochs):
            hidden_layer = self.sigmoid(np.dot(self.inputs, self.weights))
            error = self.outputs - hidden_layer
            delta = error * self.sigmoid(hidden_layer, True)
            self.weights += np.dot(self.inputs.T, delta)
            
            if epoch % 2000 == 0:
                print('\nEpoch: ', epoch)
                print('Hidden Layer: \n', hidden_layer)
                print('Error: \n', error)
                print('Weights: \n', self.weights)
            
        return hidden_layer, error, self.weights
    
    def predict(self, new_input):
        prediction = self.sigmoid(np.dot(new_input, self.weights))
        return prediction

In [17]:
NN = NeuralNetwork(X, y)

In [18]:
hidden_layer, error, weights = NN.train(epochs=10000)

Before Training:
Weights: 
 [[0.5]
 [0.5]
 [0.5]]

Epoch:  0
Hidden Layer: 
 [[0.62245933]
 [0.73105858]
 [0.73105858]
 [0.62245933]]
Error: 
 [[-0.62245933]
 [-0.73105858]
 [ 0.26894142]
 [ 0.37754067]]
Weights: 
 [[0.64160055]
 [0.40914225]
 [0.20998491]]

Epoch:  2000
Hidden Layer: 
 [[0.01153813]
 [0.01139183]
 [0.98852282]
 [0.98866836]]
Error: 
 [[-0.01153813]
 [-0.01139183]
 [ 0.01147718]
 [ 0.01133164]]
Weights: 
 [[ 4.46901753]
 [-0.01290754]
 [-4.45075236]]

Epoch:  4000
Hidden Layer: 
 [[0.00809161]
 [0.00800769]
 [0.99194328]
 [0.99202684]]
Error: 
 [[-0.00809161]
 [-0.00800769]
 [ 0.00805672]
 [ 0.00797316]]
Weights: 
 [[ 4.82379663]
 [-0.01050868]
 [-4.80893186]]

Epoch:  6000
Hidden Layer: 
 [[0.00658207]
 [0.0065214 ]
 [0.99344314]
 [0.99350358]]
Error: 
 [[-0.00658207]
 [-0.0065214 ]
 [ 0.00655686]
 [ 0.00649642]]
Weights: 
 [[ 5.03007114]
 [-0.00932079]
 [-5.01688799]]

Epoch:  8000
Hidden Layer: 
 [[0.00568732]
 [0.00563911]
 [0.99433271]
 [0.99438075]]
Error: 
 [[-0

In [19]:
NN.predict(np.array([[1, 0, 1]]))

array([[0.50283419]])

In [ ]:
q = np.array([[ 5.17598532]
              [-0.00856139]
              [-5.16387677]])

new_input = np.array([[1, 0, 1]])

sigmoid